import { jsPDF } from "jspdf";

export interface OfficialLetterPdfParams {
  companyProfile: {
    logoUrl: string;
    companyName: string;
    address: string;
    contactNumber: string;
    emailId: string;
    website: string;
  };
  letter: {
    recipientName: string;
    recipientDesignation: string;
    recipientHQ?: string;
    subject: string;
    body: string;
    date: string; // DD-MM-YYYY
    letterType: string;
    letterRefNumber?: string;
  };
  generatedBy: {
    name: string;
    designation: string;
    role: string;
  };
  generatedAt: string; // DD-MM-YYYY HH:MM
}

// Page dimensions in mm (A4 portrait)
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN_X = 15;
const HEADER_H = 60; // mm reserved at top
const FOOTER_H = 30; // mm reserved at bottom
const CONTENT_TOP = HEADER_H + 5;
const CONTENT_BOTTOM = PAGE_H - FOOTER_H - 5;
const CONTENT_W = PAGE_W - MARGIN_X * 2;

// ── Helpers ──────────────────────────────────────────────────────────────────

function drawSeparatorLine(doc: jsPDF, y: number): void {
  doc.setDrawColor(150, 150, 150);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_X, y, PAGE_W - MARGIN_X, y);
}

function setFont(
  doc: jsPDF,
  style: "normal" | "bold" | "italic",
  size: number,
): void {
  doc.setFont("helvetica", style);
  doc.setFontSize(size);
}

function addHeaderFooter(
  doc: jsPDF,
  pageNum: number,
  totalPages: number,
  params: OfficialLetterPdfParams,
  logoData: string | null,
): void {
  const { companyProfile, letter, generatedBy, generatedAt } = params;

  // ── HEADER ──
  let x = MARGIN_X;
  let y = 12;

  // Logo (left-aligned, max height 14mm ≈ 50px)
  if (logoData) {
    try {
      const imgProps = doc.getImageProperties(logoData);
      const maxH = 14;
      const ratio = imgProps.width / imgProps.height;
      const imgW = Math.min(ratio * maxH, 40);
      doc.addImage(logoData, "PNG", x, y - 2, imgW, maxH);
      x += imgW + 4;
    } catch {
      // skip logo silently
    }
  }

  // Company info block
  setFont(doc, "bold", 16);
  doc.setTextColor(30, 30, 30);
  doc.text(companyProfile.companyName, x, y);
  y += 6;

  setFont(doc, "normal", 9);
  doc.setTextColor(60, 60, 60);
  if (companyProfile.address) {
    doc.text(companyProfile.address, x, y);
    y += 4.5;
  }

  const contactLine = [companyProfile.contactNumber, companyProfile.emailId]
    .filter(Boolean)
    .join("  |  ");
  if (contactLine) {
    doc.text(contactLine, x, y);
    y += 4.5;
  }

  if (companyProfile.website) {
    doc.text(companyProfile.website, x, y);
    y += 4.5;
  }

  if (letter.letterRefNumber) {
    setFont(doc, "bold", 9);
    doc.text(`Ref No: ${letter.letterRefNumber}`, x, y);
    y += 4.5;
  }

  // Separator below header
  const sepY = Math.max(y + 2, HEADER_H - 4);
  drawSeparatorLine(doc, sepY);

  // ── FOOTER ──
  const footerTopY = PAGE_H - FOOTER_H + 2;
  drawSeparatorLine(doc, footerTopY);

  // Page number — right aligned
  setFont(doc, "normal", 8);
  doc.setTextColor(80, 80, 80);
  const pageText = `Page ${pageNum} of ${totalPages}`;
  const pageTextW = doc.getTextWidth(pageText);
  doc.text(pageText, PAGE_W - MARGIN_X - pageTextW, footerTopY + 5);

  // Generated On / By — left aligned
  doc.text(`Generated On: ${generatedAt}`, MARGIN_X, footerTopY + 5);
  doc.text(
    `Generated By: ${generatedBy.name} (${generatedBy.role})`,
    MARGIN_X,
    footerTopY + 9,
  );

  // Confidentiality notice — centered, italic
  setFont(doc, "italic", 7.5);
  doc.setTextColor(100, 100, 100);
  const notice =
    "This document is confidential and intended for internal use only.";
  const noticeW = doc.getTextWidth(notice);
  doc.text(notice, (PAGE_W - noticeW) / 2, footerTopY + 14);

  // Reset text color
  doc.setTextColor(30, 30, 30);
}

async function loadLogoAsBase64(logoUrl: string): Promise<string | null> {
  if (!logoUrl) return null;

  // Already a base64 data URL
  if (logoUrl.startsWith("data:")) return logoUrl;

  // Attempt fetch → base64 conversion
  try {
    const resp = await fetch(logoUrl, { cache: "force-cache" });
    if (!resp.ok) return null;
    const blob = await resp.blob();
    return await new Promise<string | null>((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// ── PDF generation ────────────────────────────────────────────────────────────

async function buildPdf(params: OfficialLetterPdfParams): Promise<jsPDF> {
  const { letter, generatedBy, generatedAt } = params;

  // Load logo once
  const logoData = await loadLogoAsBase64(params.companyProfile.logoUrl);

  // ── First pass: render content to figure out page count ──
  // We use a two-pass approach: collect all "lines" to print, then render.

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Build content lines array
  type ContentLine = {
    text: string;
    style: "normal" | "bold" | "italic";
    size: number;
    gap?: number; // extra gap BEFORE this line
  };

  const lines: ContentLine[] = [];

  // Letter date
  lines.push({
    text: `Date: ${letter.date}`,
    style: "normal",
    size: 11,
    gap: 0,
  });
  lines.push({ text: "", style: "normal", size: 11, gap: 3 });

  // To block
  const recipientParts = [
    letter.recipientName,
    letter.recipientDesignation,
    letter.recipientHQ,
  ]
    .filter(Boolean)
    .join(", ");
  lines.push({ text: "To,", style: "normal", size: 11 });
  lines.push({ text: recipientParts, style: "normal", size: 11 });
  lines.push({ text: "", style: "normal", size: 11, gap: 3 });

  // Subject (bold)
  lines.push({ text: `Subject: ${letter.subject}`, style: "bold", size: 11 });
  lines.push({ text: "", style: "normal", size: 11, gap: 3 });

  // Body paragraphs
  const paragraphs = letter.body.split("\n");
  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) {
      lines.push({ text: "", style: "normal", size: 11, gap: 2 });
      continue;
    }
    // Split long paragraphs to fit content width
    setFont(doc, "normal", 11);
    const wrapped = doc.splitTextToSize(trimmed, CONTENT_W);
    for (const wl of wrapped as string[]) {
      lines.push({ text: wl, style: "normal", size: 11 });
    }
    lines.push({ text: "", style: "normal", size: 11, gap: 2 });
  }

  // ── Second pass: render pages ──
  // We'll track pages as arrays of content indices, then render.
  // Strategy: walk lines, track y. On overflow → new page.

  // Pre-calculate signatory block height (rendered on last page above footer)
  const SIGNATORY_H = 40; // mm (title + gap + name + desig + company + date)

  // Gather page breaks
  const lineHeightBase = 6; // mm per line at 11pt
  let y = CONTENT_TOP;
  const pageBreaks: number[] = [0]; // index into lines[] where each page starts

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lh = line.gap ? line.gap + lineHeightBase : lineHeightBase;
    // Reserve signatory space on the (tentative) last page — we'll refine below
    if (y + lh > CONTENT_BOTTOM) {
      pageBreaks.push(i);
      y = CONTENT_TOP;
    }
    y += lh;
  }

  // Check if signatory fits on last page
  // (y holds current y after last line on last page)
  if (y + SIGNATORY_H > CONTENT_BOTTOM) {
    pageBreaks.push(lines.length); // signatory on a new (empty) page
  }

  const finalTotalPages = pageBreaks.length;

  // ── Render ──
  for (let p = 0; p < finalTotalPages; p++) {
    if (p > 0) doc.addPage();

    addHeaderFooter(doc, p + 1, finalTotalPages, params, logoData);

    const startLine = pageBreaks[p];
    const endLine = pageBreaks[p + 1] ?? lines.length;

    let cy = CONTENT_TOP;

    for (let i = startLine; i < endLine; i++) {
      const line = lines[i];
      if (line.gap) cy += line.gap;

      if (line.text) {
        setFont(doc, line.style, line.size);
        doc.setTextColor(30, 30, 30);
        doc.text(line.text, MARGIN_X, cy);
      }
      cy += lineHeightBase;
    }

    // ── Authorized Signatory on LAST page ──
    if (p === finalTotalPages - 1) {
      const sigY = CONTENT_BOTTOM - SIGNATORY_H + 5;

      setFont(doc, "bold", 11);
      doc.setTextColor(30, 30, 30);
      doc.text("Authorized Signatory", MARGIN_X, sigY);

      // Signature blank space (~15mm)
      const sigLineY = sigY + 18;
      doc.setDrawColor(80, 80, 80);
      doc.setLineWidth(0.3);
      doc.line(MARGIN_X, sigLineY, MARGIN_X + 60, sigLineY);

      setFont(doc, "normal", 10);
      let sy = sigLineY + 5;
      doc.text(generatedBy.name, MARGIN_X, sy);
      sy += 5;
      doc.text(generatedBy.designation, MARGIN_X, sy);
      sy += 5;
      doc.text(params.companyProfile.companyName, MARGIN_X, sy);
      sy += 5;
      // Extract date portion from generatedAt (DD-MM-YYYY HH:MM)
      const datePortion = generatedAt.split(" ")[0] ?? generatedAt;
      doc.text(`Date: ${datePortion}`, MARGIN_X, sy);
    }
  }

  return doc;
}

// ── Public exports ────────────────────────────────────────────────────────────

export async function generateOfficialLetterPdf(
  params: OfficialLetterPdfParams,
): Promise<Blob> {
  const doc = await buildPdf(params);
  return doc.output("blob");
}

export async function downloadOfficialLetterPdf(
  params: OfficialLetterPdfParams,
): Promise<void> {
  const doc = await buildPdf(params);
  const fileName = getPdfFileName(
    params.letter.letterType,
    params.letter.recipientName,
    params.letter.date,
  );
  doc.save(fileName);
}

export function getPdfFileName(
  letterType: string,
  recipientName: string,
  date: string,
): string {
  const safeName = recipientName.replace(/\s+/g, "_");
  const safeDate = date.replace(/\s+/g, "_");

  const typeMap: Record<string, string> = {
    Appointment: `Appointment_Letter_${safeName}_${safeDate}.pdf`,
    "Leave Approval": `Leave_Approval_${safeName}_${safeDate}.pdf`,
    "Leave Rejection": `Leave_Rejection_${safeName}_${safeDate}.pdf`,
    "Warning Letter": `Warning_Letter_${safeName}_${safeDate}.pdf`,
    Warning: `Warning_Letter_${safeName}_${safeDate}.pdf`,
    Experience: `Experience_Letter_${safeName}_${safeDate}.pdf`,
    "Show Cause": `Show_Cause_Notice_${safeName}_${safeDate}.pdf`,
    "Confirmation Letter": `Confirmation_Letter_${safeName}_${safeDate}.pdf`,
    Confirmation: `Confirmation_Letter_${safeName}_${safeDate}.pdf`,
    "Transfer Letter": `Transfer_Letter_${safeName}_${safeDate}.pdf`,
    Transfer: `Transfer_Letter_${safeName}_${safeDate}.pdf`,
    "Promotion Letter": `Promotion_Letter_${safeName}_${safeDate}.pdf`,
    Promotion: `Promotion_Letter_${safeName}_${safeDate}.pdf`,
    "Increment Letter": `Increment_Letter_${safeName}_${safeDate}.pdf`,
    Increment: `Increment_Letter_${safeName}_${safeDate}.pdf`,
    "Termination Letter": `Termination_Letter_${safeName}_${safeDate}.pdf`,
    Termination: `Termination_Letter_${safeName}_${safeDate}.pdf`,
  };

  if (typeMap[letterType]) return typeMap[letterType];

  const safeType = letterType.replace(/\s+/g, "_");
  return `Official_Letter_${safeType}_${safeName}_${safeDate}.pdf`;
}
